### ISSUE TITLE
Not compatible with Stardew Valley 1.1+

### ISSUE THREAD

**Issue by Pathoschild** [CJBok/SDV-Mods#1]
Hi! These mods aren't compatible with the latest version of Stardew Valley, but they're still very popular. If I submit a pull request and attach the compiled versions, any chance you could upload them to the mod pages on Nexus?

**Comment by CJBok** [comment]
I mate, that would be awesome. Don't have much time on my hands atm!

**Comment by Pathoschild** [comment]
@CJBok ready to merge with pull request #2. :)

If you have no objections, I'll release unofficial betas on the forums to make sure everything works fine, then attach the final builds once they're ready to publish.

**Comment by CJBok** [comment]
When you have the compiled version ready send me the links. Also make sure you credit yourself in the compiled version. ;)

Awesome work mate! I really appriciate this!

**Comment by Pathoschild** [comment]
@CJBok Pull request #3 is ready to merge; it incorporates some updates and fixes by @huancz for CJB Automation, who unofficially updated the mod in the Chucklefish forums. :)

**Comment by Pathoschild** [comment]
Beta posts:
* [CJB Automation 1.4-beta](http://community.playstarbound.com/threads/smapi-0-39-6-cjb-automation-v1-3-02-apr-2016.112000/page-8#post-3085571)
* [CJB Cheats Menu 1.13-beta](http://community.playstarbound.com/threads/smapi-0-40-0-in-game-cheat-menu-v1-12-09-apr-2016.108004/page-45#post-3085130)
* [CJB Item Spawner 1.6-beta](http://community.playstarbound.com/threads/smapi-0-39-6-cjb-item-spawner-v1-5-02-apr-2016.110257/page-9#post-3085131)

I didn't find a thread for CJB Show Item Sell Price, but that one didn't change much and is the easiest one to test anyway.

**Comment by CJBok** [comment]
Updated the posts, thank you very much!

http://community.playstarbound.com/threads/smapi-0-39-6-cjb-show-item-sell-price-v1-5-30-mar-2016.107854/

**Comment by Pathoschild** [comment]
Here are the compiled stable releases, ready to publish at your convenience:
* [CJBAutomation 1.4.zip](https://github.com/CJBok/SDV-Mods/files/683274/CJBAutomation.1.4.zip)
* [CJBCheatsMenu 1.13.zip](https://github.com/CJBok/SDV-Mods/files/683275/CJBCheatsMenu.1.13.zip)
* [CJBItemSpawner 1.6.zip](https://github.com/CJBok/SDV-Mods/files/683276/CJBItemSpawner.1.6.zip)
* [CJBShowItemSellPrice 1.6.zip](https://github.com/CJBok/SDV-Mods/files/683277/CJBShowItemSellPrice.1.6.zip)

For the Nexus mod pages, I suggest linking directly to the [SMAPI releases](https://github.com/Pathoschild/SMAPI/releases) (more intuitive than the forums), recommending the 'latest version of SMAPI' instead of SMAPI 0.37 (which won't work), and briefly documenting how to install the mods. (See the [LookupAnything page](http://www.nexusmods.com/stardewvalley/mods/541/) for an example of what I suggest.) If you want, temporarily add me as a team member on the Nexus mod pages (via 'edit attributes') and I'll update the pages for you. :)

**Comment by CJBok** [comment]
Added you as team member on nexus. :)

**Comment by Pathoschild** [comment]
@CJBok I updated [CJB Automation](http://www.nexusmods.com/stardewvalley/mods/211/) and sorted through the open bugs. Does that look OK? If so I'll do the other mods.

**Comment by Pathoschild** [comment]
@CJBok all Nexus pages updated:
* [CJB Automation 1.4](http://www.nexusmods.com/stardewvalley/mods/211)
* [CJB Cheats Menu 1.13](http://www.nexusmods.com/stardewvalley/mods/4)
* [CJB Item Spawner 1.6](http://www.nexusmods.com/stardewvalley/mods/93/)
* [CJB Show Item Sell Price 1.6](http://www.nexusmods.com/stardewvalley/mods/5)

I attached the [original mod descriptions](https://github.com/CJBok/SDV-Mods/files/690699/2016-01-07.original.mod.descriptions.txt) if you want them.

Feel free to remove me from the teams (unless you'd like me to keep the pages updated longer-term).
