### ISSUE TITLE
[CJB Item Spawner]Problem with the toolbox size

### ISSUE THREAD

**Issue by Andremamanks** [CJBok/SDV-Mods#120]
So the problem is about the size of the toolbox because it's oversized, A smartphone with a 5.0-inch screen can't fit that wide, please fix that fast
Because I am want to press the misc button by the way the search,misc button,trashcan, are almost not show on my screen please please....!

**Comment by Pathoschild** [comment]
Can you post a screenshot of the menu on your phone?

**Comment by Andremamanks** [comment]
![Screenshot_2020-08-01-11-25-06-483_com zane stardewvalley](https://user-images.githubusercontent.com/61966036/89094149-2df49380-d3eb-11ea-9666-a0d5b09bfa3e.jpg)
So this is how it look like

**Comment by Pathoschild** [comment]
Thanks! I created #121 to track known Android issues, so I'll close this one.
