### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Dhanamerdeka** [CJBok/SDV-Mods#123]
Ummm are u guys want to implement
like... https://www.nexusmods.com/stardewvalley/mods/1150
Shown which cows that ready for milking, or see blacksmith progress....
i think this will be amazing....
also feature like... shown require or coverage tiles for tree, springkler, or scarecrow

**Comment by Dhanamerdeka** [comment]
and also if you implement this to cjb menu it will be great i think
https://www.nexusmods.com/stardewvalley/mods/4430

**Comment by Pathoschild** [comment]
Hi! CJB Cheats Menu is an in-game cheat utility, it's not meant to unify many different mods into one (which would be hard to maintain). You can safely use it alongside the other mods instead.
