### ISSUE TITLE
[Request] [CJB Cheats Menu] Add support to multiple keybindings

### ISSUE THREAD

**Issue by Caco-o-sapo** [CJBok/SDV-Mods#139]
Adding the support for different keybindings, or separate keybindings for keyboard or controller, more specifically for split-screen. 

Example: I use the keyboard and my sister uses the controller, she wants to open the CBJ Cheats Menu, but it's only possible for me to open it. 

I hope that I got to the right place for this, they said to come here.

**Comment by Pathoschild** [comment]
Ideally I'd want to support the multi-key format I use in my own mods (like `"P, LeftShoulder + ControllerA"`), but SMAPI doesn't have an API for that yet. I'll look into adding an API in upcoming SMAPI versions for CJB mods to use too.

**Comment by Pathoschild** [comment]
Done in the upcoming CJB Cheats Menu 1.28.

**Comment by AaronCompNetSys** [comment]
I'm now in the same scenario playing split screen with my wife on Windows with Xbone wireless controllers. I only see the ability to assign one keyboard key for player one and when I try reassign something on either of our controllers nothing happens. I'm using 1.29.3 on top of sve modpack, everything latest.

**Comment by Pathoschild** [comment]
The in-game config UI doesn't support it directly, but you can [set alternate keybinds directly in `config.json`](https://stardewvalleywiki.com/Modding:Player_Guide/Key_Bindings) just like for other mods.

**Comment by Pathoschild** [comment]
@AaronCompNetSys The keybind activates the menu for the player who pressed it. For example, if you set this:
```json
"OpenMenuKey": "P, LeftShoulder + RightShoulder",
```
...then when player 2 presses the shoulder buttons, the menu will open on their screen (and not on other players' screens).
