### ISSUE TITLE
[Bug] CJB Item Spawner : Type letter "E" in search bar will clear all entered words

### ISSUE THREAD

**Issue by horizon98** [CJBok/SDV-Mods#145]
Using 2.1.0, when I type letter "E" in the search bar will clear all entered words. In a very rare case which I can't reproduce, type letter "Y" in the search bar will close the CJB tab and pop up emote menu. Version 2.0.2 dosen't have this problem.

See also: [Posts on NexusMods](https://forums.nexusmods.com/index.php?showtopic=3907762/#entry92143408)

![image](https://user-images.githubusercontent.com/48114360/111896000-826b8280-8a51-11eb-8d7e-45b1e7465f82.gif)

**Comment by Pathoschild** [comment]
Fixed in the upcoming CJB Cheats Menu 2.1.1. Thanks for reporting it!
