### ISSUE TITLE
[CJB Item Spawner] Can't display all catagories tag

### ISSUE THREAD

**Issue by ellipszist** [CJBok/SDV-Mods#146]
![Alt Text](https://cdn.discordapp.com/attachments/693528911862300802/831944641078886410/Screenshot_20210415-003332.jpg)

Can you add some scrollbar or slide menu to catagories box. 

Ps. My device is  samsung galaxy note 20 ultra. Still can't see all...

**Comment by Pathoschild** [comment]
A scroll arrow should appear automatically. Can you try it again, then [upload your SMAPI log](https://smapi.io/log) (see instructions on that page) and post a link here?

**Comment by ellipszist** [comment]
> A scroll arrow should appear automatically. Can you try it again, then [upload your SMAPI log](https://smapi.io/log) (see instructions on that page) and post a link here?

https://smapi.io/log/d00e22a465b743dbbc87ba3a4bf6977b

**Comment by Pathoschild** [comment]
Newer versions of CJB Item Spawner have some changes that may fix that. Unfortunately I can't really support older versions, but if it still happens when Android gets the latest game version, feel free to post a bug report on the mod page!
