### ISSUE TITLE
[CJB Cheats Menu] No Friendship Decay for Animals

### ISSUE THREAD

**Issue by strobel1ght** [CJBok/SDV-Mods#149]
Seems like a feature that could fit within Cheat Menu's scope!
https://stardewvalleywiki.com/Animals#Friendship

> 
> Not Fed (-20 Calculated day-end)
> Trapped outside overnight (-20 Calculated day-end)
> Not Petted/Talked to (-5 to -10, Calculated day-end by the formula: (10 - (CurrentFriendship / 200))) This means they will lose less friendship, if they are already high friendship.

**Comment by Pathoschild** [comment]
Added in CJB Cheats Menu 1.29.0 via #150. Thanks!
