### ISSUE TITLE
Add function (menu button or console command) to reload the warps file from disk

### ISSUE THREAD

**Issue by PrincessRTFM** [CJBok/SDV-Mods#160]
Particularly when updating a `warps.json` file for mods that change or add maps, it would be very convenient if the list of warps could be reloaded from disk without needing to restart the entire game. Either a button (probably in the warps section of the menu) or a console command (like `cjb_reload_warps` for instance) to do this would make creating expanded warp lists a lot easier.

**Comment by Pathoschild** [comment]
Console command added via #172 in the upcoming CJB Cheats Menu 1.31.0. Thanks for the suggestion!
