### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by ChulkyBow** [CJBok/SDV-Mods#165]
Could Polish translation be added to CJB Item Spawner mod? 

CJB Item Spawner Polish :  [https://www.nexusmods.com/stardewvalley/mods/8614](https://www.nexusmods.com/stardewvalley/mods/8614)

P.S : Yes, there is already a Polish modification for Stardew Valley 1.5.5 beta, which adds a new custom language to the game (obviously it's Polish). Polish mod for SDV : [https://www.nexusmods.com/stardewvalley/mods/3616](https://www.nexusmods.com/stardewvalley/mods/3616).

**Comment by ChulkyBow** [comment]
I just don't know how to open a new empty branch instead of adding it to another :sweat_smile:

**Comment by Pathoschild** [comment]
Hi! Anyone can contribute translations for the mod. I can't take the translations directly from the mod page due to copyright, but if you're fine publishing them under [CJB Item Spawner's open-source license](https://github.com/CJBok/SDV-Mods/blob/master/LICENSE), you can post the translation file here and I'll add it in the next version.

**Comment by ChulkyBow** [comment]
> Hi! Anyone can contribute translations for the mod. I can't take the translations directly from the mod page due to copyright, but if you're fine publishing them under [CJB Item Spawner's open-source license](https://github.com/CJBok/SDV-Mods/blob/master/LICENSE), you can post the translation file here and I'll add it in the next version.

Okay, thanks)
[CJBItemSpawner - Spolszczenie 1.1(SDV 1.5.5. beta).zip](https://github.com/CJBok/SDV-Mods/files/7625454/CJBItemSpawner.-.Spolszczenie.1.1.SDV.1.5.5.beta.zip)

**Comment by Pathoschild** [comment]
Added in the upcoming CJB Item Spawner 2.1.6. Thanks for the help!
