### ISSUE TITLE
Seasonal Immersion flowers not showing up in CJB Item Spawner

### ISSUE THREAD

**Issue by eemiestardewvalley** [CJBok/SDV-Mods#18]
People have been reporting to me, as of date June 5th, that the flowers (found [here](http://www.nexusmods.com/stardewvalley/mods/891/?tab=4&&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fstardewvalley%2Fajax%2Fcomments%2F%3Fmod_id%3D891%26page%3D1%26sort%3DDESC%26pid%3D0%26thread_id%3D5328715&pUp=1), which can be accessed by spawning them in through CJB item spawner) fail to show up in the CJB Item Spawner. My guess is that they are using version 1.8 rather than version 1.7.2. I had Fan test this out for me and he (while using SMAPI 1.4) basically confirmed that they don't show up in 1.8 but they do in 1.7.2.

Firs image previews the flowers that should show up, using 1.7.2. Second image previews the flowers failing to show up, using 1.8. (Ignore the potted flowers, they come with my furniture mod and have nothing to do with this).

![image](https://user-images.githubusercontent.com/29406684/27089304-4bbaa458-505a-11e7-8b5a-c1974904bd3d.png)

![image](https://user-images.githubusercontent.com/29406684/27089342-66c05e46-505a-11e7-9da4-7dbe3cd2c3a5.png)

**Comment by grandpawiggler** [comment]
In 1.8, the flowers nor the flower bush do not appear. However, in 1.7.2, 1.7.1, and 1.7.0 the flower bush does appear and the flowers do not.

**Comment by Pathoschild** [comment]
Fixed in the next version of CJB Item Spawner. Thanks to @Platonymous for the pull request!
