### ISSUE TITLE
Item spawner and cheat menu 

### ISSUE THREAD

**Issue by utilebread** [CJBok/SDV-Mods#187]
The item spawner and cheat menu for Android are to big and I cant use some functions ![Screenshot_20221024-090105.png](https://user-images.githubusercontent.com/101355543/197568921-b30d4403-ebf5-4cff-8120-f8cda1cb2f23.png)

**Comment by Pathoschild** [comment]
Hi! Newer versions have already been redesigned for mobile support:
> ![image](https://user-images.githubusercontent.com/230581/198889514-2ed4fcff-593a-4145-b858-7bdae5e1b79c.png)

You should be able to use the newer versions once you get Stardew Valley 1.5+ on Android.

**Comment by utilebread** [comment]
Where can I find it?

**Comment by Pathoschild** [comment]
It's the main download on the [CJB Item Spawner mod page](https://www.nexusmods.com/stardewvalley/mods/93), but it won't work on Android until you get the newer game update.
