### ISSUE TITLE
Interface bug on Android

### ISSUE THREAD

**Issue by pesadeloUnk** [CJBok/SDV-Mods#200]
**The interface box where the items should be is very small, and it only shows one item, I can search the name of the item and it doesn't change, it still stays the same, my phone is a moto e6s and the android version is 9**
![Screenshot_20230725-184941](https://github.com/CJBok/SDV-Mods/assets/140560588/dfad3135-3427-4d63-b1f9-4b2073dff217)

**Comment by unknownuserbr** [comment]
I'm having this exact same problem

**Comment by pesadeloUnk** [comment]
> I'm having this exact same problem

Although I couldn't solve the problem, I found that version 1.11.5 of the mod works normally, but obviously the new items are not available in the menu.

**Comment by Pathoschild** [comment]
Hi! I'll close this ticket since I don't track support questions on GitHub, but feel free to come [discuss on the mod page](https://www.nexusmods.com/stardewvalley/mods/93/?tab=posts) if you want to help test possible Android compatibility fixes.
