### ISSUE TITLE
Configurable speed for fast machine processing

### ISSUE THREAD

**Issue by xMooshyx** [CJBok/SDV-Mods#220]
So I’ve been using this cheat menu mod for many years now. And the only thing I have an issue with is that the fast machine processing is way to fast. I tried using the Automate mod with it and set that to the longest interval timer available but its still too fast for my liking.
Is it possible to add a configuration option for this so I can set the fast machine processing to like once a day or something?

Thanks!

**Comment by Pathoschild** [comment]
Hi! CJB Cheats Menu focuses on simple cheats which are usually on/off. To configure specific things more granularly like that, you can try a more specialized mod like [Configure Machine Speed](https://www.nexusmods.com/stardewvalley/mods/21005) (which should work fine alongside CJB Cheats Menu).
