### ISSUE TITLE
[CJB Cheats Menu] Broken on latest beta

### ISSUE THREAD

**Issue by SHADOW-REX** [CJBok/SDV-Mods#227]
On SMPAI 4.1.0-beta1 both of the mods, "CJB Cheats Menu" and "Chests Anywhere", worked absolutely fine.

But with the latest beta update of StardewValley and SMAPI 4.1.0-beta2 , both of these mods broke:
```
﻿CJB Cheats Menu 1.37.0-beta.20240818 because it's no longer compatible. Please check for a new version at https://smapi.io/mods
﻿Chests Anywhere 1.24.2-beta.20240818 because it's no longer compatible.
```

Now, with SMAPI 4.1.0-beta3 released, 
Chests Anywhere started working 
but CJB Cheats Menu still remains broken

PS: It's either some issue with the mod or SMAPI.

**Comment by Pathoschild** [comment]
That should already be fixed in newer beta versions of those mods. (It was due to a change in the Stardew Valley beta.) Thanks for reporting it!
