### ISSUE TITLE
[CJB Item Spawner] Pickle Varieties don't appear in search results

### ISSUE THREAD

**Issue by danvolchek** [CJBok/SDV-Mods#31]
Pickle varieties don't appear in the search results of CJB Item Spawner because `yield return pickled;` is missing after the pickled items are created in `ItemMenu.GetSpawnableItems`, more specifically after line 602 of `ItemMenu.cs` in the develop branch.

**Comment by Pathoschild** [comment]
Fixed in the upcoming CJB Item Spawner 1.11-beta.2. Thanks!
