### ISSUE TITLE
[CJB Item Spawner] Non-base artisan goods always spawn at regular quality

### ISSUE THREAD

**Issue by danvolchek** [CJBok/SDV-Mods#37]
Spawned wine, pickled items, honey, jelly, and juice that are not the base item are always regular quality, regardless of what quality you choose through the `Quality` button.

For example, spawning iridium quality `Juice` works, but not `Amaranth Juice` or any other type of `Juice`, and the same occurs for the other artisan goods mentioned.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming CJB Item Spawner 1.11-beta.3. Thanks for reporting it!
