### ISSUE TITLE
CJB Show Item Sell Price Simplified Chinese Translation

### ISSUE THREAD

**Issue by BerryConcept** [CJBok/SDV-Mods#54]
I have done the Simplified Chinese translation for CJB Show Item Sell Price mod. Please take a look and hope it will help.
[zh.zip](https://github.com/CJBok/SDV-Mods/files/2640861/zh.zip)

**Comment by Pathoschild** [comment]
Thanks! Someone else already translated it for the upcoming CJB Show Item Sell Price 1.9.2 (see [latest version](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/zh.json)). Let me know if you want to make any changes.

**Comment by Pathoschild** [comment]
Understandable is fine. It doesn't need to exactly match the wiki, as long as it's not confusing.

**Comment by BerryConcept** [comment]
Cool then. I'll try to translate more mod as long as I have some time. I'll follow the posted mods first you provided on nexus.
