### ISSUE TITLE
CJB Item Spawner Simplified Chinese Translation

### ISSUE THREAD

**Issue by BerryConcept** [CJBok/SDV-Mods#55]
I have done the Simplified Chinese translation for CJB Item Spawner mod. Please take a look and hope it will help.
[zh.zip](https://github.com/CJBok/SDV-Mods/files/2640873/zh.zip)

**Comment by Pathoschild** [comment]
Thanks! I merged your translations with those provided by another user (see [latest version](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/zh.json)). Let me know if you want to make any changes. They'll be released in CJB Item Spawner 1.11.2.

**Comment by Pathoschild** [comment]
Understandable is fine. It doesn't need to exactly match the wiki, as long as it's not confusing.

**Comment by BerryConcept** [comment]
Cool then. I'll try to translate more mod as long as I have some time. I'll follow the posted mods first you provided on nexus.
