### ISSUE TITLE
[CJB Cheats Menu] French translation

### ISSUE THREAD

**Issue by Mysti57** [CJBok/SDV-Mods#62]
Hello,

I'm a French user of your Mod "CJB Cheats Menu", i have translate it to my language, guess it's help you !

[fr.zip](https://github.com/CJBok/SDV-Mods/files/2971334/fr.zip)

**Comment by Pathoschild** [comment]
Thanks! The mod was already [translated into French](https://github.com/CJBok/SDV-Mods/blob/develop/CJBCheatsMenu/i18n/fr.json) in the upcoming version though. Let me know if you suggest any changes to the current translations though!

**Comment by Mysti57** [comment]
There are a typo line 46, the correct word is 
"fast-machines.title": "Tr**ans**formation rapide ", 
and not
"fast-machines.title": "Trasnformation rapide ",
