### ISSUE TITLE
[CJB Item Spawner] French translation

### ISSUE THREAD

**Issue by Mysti57** [CJBok/SDV-Mods#64]
Hello,

I'm a French user of your Mod "CJB Item Spawner", i have translate it to my language, guess it's help you !

[fr.zip](https://github.com/CJBok/SDV-Mods/files/2971367/fr.zip)

**Comment by Pathoschild** [comment]
Thanks! The mod was already [translated into French](https://github.com/CJBok/SDV-Mods/blob/develop/CJBItemSpawner/i18n/fr.json) in the upcoming version though. Let me know if you suggest any changes to the current translations though!
