### ISSUE TITLE
[CJB Show Item Sell Price] French translation

### ISSUE THREAD

**Issue by Mysti57** [CJBok/SDV-Mods#65]
Hello,

I'm a French user of your Mod "CJB Show Item Sell Price", i have translate it to my language, guess it's help you !

[fr.zip](https://github.com/CJBok/SDV-Mods/files/2971416/fr.zip)

**Comment by Pathoschild** [comment]
Thanks! The mod was already [translated into French](https://github.com/CJBok/SDV-Mods/blob/develop/CJBShowItemSellPrice/i18n/fr.json) in the upcoming version though. Let me know if you suggest any changes to the current translations though!
