### ISSUE TITLE
[CJB Cheats Menu] Config Setting to Customize the Size of Instant Grow Area

### ISSUE THREAD

**Issue by Ikenowski** [CJBok/SDV-Mods#69]
Would it be possible to add a setting in the config to customize the size of the area the instant grow option affects?

**Comment by Pathoschild** [comment]
That was added in CJB Cheats Menu 1.23:
![image](https://user-images.githubusercontent.com/230581/78518476-96f63280-778e-11ea-9f52-10f76e761359.png)
