### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by Pathoschild** [CJBok/SDV-Mods#7]
@CJBok: Can you [choose an open-source license](https://choosealicense.com/) for your mods? I'd like to encourage [community maintenance](https://github.com/Pathoschild/StardewCommunityMods#readme) of the mods. :)

**Comment by Pathoschild** [comment]
@CJBok: any interest in doing this, or would you prefer not?

**Comment by afaur** [comment]
Hello @CJBok ,

I would like to also like to see if you are interested in doing this. 👍

Here are some helpful resources on the `why` from the `github` side: 
https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license
https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users

Here is some info on how to include a license:
https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository

If you are interested in some very simple `open licenses` I can recommend these two:
- MIT (https://opensource.org/licenses/MIT)
- Unlicense (http://unlicense.org/)

I have found that this is a helpful site for finding the right license: https://choosealicense.com/

**Comment by CJBok** [comment]
#20 added

**Comment by Pathoschild** [comment]
Thanks!
