### ISSUE TITLE
Release dlls too?

### ISSUE THREAD

**Issue by stepquick** [CJBok/SDV-Mods#83]
Could these mods be built and the bin folder be released as the final product in addition to the zipped project? The instructions aren't very clear on how to build these manually. I ended up to set files to copy on build to get descriptions to work properly. Maybe I did something wrong? Thanks. These plugins work fairly well once I got them installed.

**Comment by Pathoschild** [comment]
There's no need to compile the mods yourself unless you're making changes. You can download compiled versions from the [Nexus Mods pages](https://www.nexusmods.com/stardewvalley/users/3108607?tab=user+files) (requires a free account).

**Comment by stepquick** [comment]
Yeah I know about nexus mods, I'll just close this. I don't really care to create a nexus mod account.
