### ISSUE TITLE
[CJB Cheats Menu] Persistent speed debuff after events if the speed cheat is enabled

### ISSUE THREAD

**Issue by Pathoschild** [CJBok/SDV-Mods#86]
If you have the speed cheat enabled and watch a cutscene, you'll have a persistent speed debuff after it ends. The effect stacks if you see multiple events.

[Reported on Nexus](https://www.nexusmods.com/stardewvalley/mods/4/?tab=bugs&issue_id=432043).

**Comment by jdusbabek** [comment]
There might be side effects I'm not aware of yet; and there may be other advantages to having movement speed implemented as a speed buff... but I was able to work around this issue by replacing the entire block of buff code in UpdateBuff() with:  Game1.player.addedSpeed = this.Config.MoveSpeed;

**Comment by Pathoschild** [comment]
The main side effect of that is incompatibility with other mods and issues with in-game buffs, if I remember correctly.

**Comment by Pathoschild** [comment]
This is an issue with Entoarox Framework; removing that mod should fix it. I reported it to that mod's author.
