### ISSUE TITLE
[CJB Cheats Menu] add “unlimited items” function

### ISSUE THREAD

**Issue by suiahae** [CJBok/SDV-Mods#97]
Consider adding `unlimited items` function.

**Comment by Pathoschild** [comment]
You can use [CJB Item Spawner](https://www.nexusmods.com/stardewvalley/mods/93) to get any number of an item.

**Comment by suiahae** [comment]
> You can use [CJB Item Spawner](https://www.nexusmods.com/stardewvalley/mods/93) to get any number of an item.

Thank you very much!
