### ISSUE TITLE
[CJB Item Spawner] search box doesn't work on Android

### ISSUE THREAD

**Issue by Pathoschild** [CJBok/SDV-Mods#99]
The menu itself works fine on Android (as of CJB Item Spawner 1.11.6), but tapping the search box doesn't do anything.

**Comment by xniicolax** [comment]
Thanks for fixing the menu! Just let me know when the keyboard is fixed :) thanks!

**Comment by Pathoschild** [comment]
This should be fixed in newer versions of SMAPI on Android.
